# Generated by Django 4.2.7 on 2023-12-08 02:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chatbot_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="qacache",
            name="created_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 12, 8, 2, 31, 39, 804707, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AddField(
            model_name="qacache",
            name="question_id",
            field=models.CharField(default="string", max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="qacache",
            name="question",
            field=models.TextField(),
        ),
    ]
