# Generated by Django 4.2.7 on 2023-12-08 02:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chatbot_app", "0002_qacache_created_time_qacache_question_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="qacache",
            name="created_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 12, 8, 2, 33, 21, 882430, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
