# Generated by Django 4.2.7 on 2023-12-08 06:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chatbot_app", "0003_alter_qacache_created_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="qacache",
            name="created_time",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="qacache",
            name="question",
            field=models.TextField(unique=True),
        ),
    ]
